/* Do not edit this file. It was automatically generated. */

#ifndef HEADER_Battery
#define HEADER_Battery
/*
htop - darwing/Battery.h
Copyright (c) 2015, Nicolas Despres
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.

Based on freebsd/Battery.c
(C) 2014 Hisham H. Muhammad
Released under the GNU GPL, see the COPYING file
in the source distribution for its full text.
*/

void Battery_getData(double* level, ACPresence* isOnAC);


#endif
